# Generated by Django 5.2.4 on 2025-08-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ('-issued_at',)},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ('-joined_at',)},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='examresult',
            options={'ordering': ('-graded_at',)},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='course',
            name='duration_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='course',
            name='teams_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('pending', 'بانتظار'), ('expired', 'منتهي')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='teams_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student'], name='students_en_student_167e75_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course'], name='students_en_course__c45ec9_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['status'], name='students_en_status_c844f7_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['student'], name='students_ex_student_ce8702_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['exam'], name='students_ex_exam_id_1b4587_idx'),
        ),
    ]
