# Generated by Django 5.2.4 on 2025-08-19 01:51

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_certificate_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='course',
            name='cover_image_url',
            field=models.URLField(blank=True, validators=[students.models.validate_https]),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file_url',
            field=models.URLField(blank=True, validators=[students.models.validate_https]),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='teams_link',
            field=models.URLField(blank=True, validators=[students.models.validate_https]),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='teams_link',
            field=models.URLField(blank=True, validators=[students.models.validate_https]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file_url',
            field=models.URLField(validators=[students.models.validate_https]),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['student'], name='students_ce_student_4a1189_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['course'], name='students_ce_course__3ae4a3_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['issued_at'], name='students_ce_issued__f0ffe3_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['title'], name='students_co_title_92a666_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active'], name='students_co_is_acti_df51af_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['joined_at'], name='students_en_joined__e210eb_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['course'], name='students_ex_course__74ede8_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['date'], name='students_ex_date_4930dd_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['graded_at'], name='students_ex_graded__13f8f1_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['title'], name='students_re_title_541744_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['is_public'], name='students_re_is_publ_1de287_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='uq_enrollment_student_course'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(('progress__gte', 0), ('progress__lte', 100)), name='ck_progress_0_100'),
        ),
        migrations.AddConstraint(
            model_name='examresult',
            constraint=models.UniqueConstraint(fields=('student', 'exam'), name='uq_examresult_student_exam'),
        ),
    ]
