# Generated by Django 5.2.4 on 2025-08-22 20:25

import django.db.models.deletion
import django.utils.timezone
import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_enrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveIndex(
            model_name='resource',
            name='students_re_title_541744_idx',
        ),
        migrations.RemoveIndex(
            model_name='resource',
            name='students_re_is_publ_1de287_idx',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='is_public',
        ),
        migrations.AddField(
            model_name='resource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='external_link',
            field=models.URLField(blank=True, validators=[students.models.validate_https]),
        ),
        migrations.AddField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/files/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='kind',
            field=models.CharField(choices=[('file', 'ملف'), ('link', 'رابط'), ('note', 'ملاحظة')], default='file', max_length=10),
        ),
        migrations.AddField(
            model_name='resource',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='students.course'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issued_at',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['course'], name='students_re_course__374972_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['kind'], name='students_re_kind_e8f0ab_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['created_at'], name='students_re_created_997199_idx'),
        ),
    ]
