# Generated by Django 5.2.4 on 2025-08-15 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_description'),
        ('students', '0002_alter_certificate_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='course',
            field=models.ForeignKey(blank=True, help_text='اختياري: اربط هذا المنتج بدورة ليظهر للطالب تلقائيًا بعد الإتمام.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='students.course', verbose_name='الدورة المرتبطة (لوحة الطالب)'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['available'], name='store_produ_availab_d58b50_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='store_produ_created_5555f3_idx'),
        ),
    ]
