# Generated by Django 5.2.4 on 2025-08-19 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_course_and_more'),
        ('teachers', '0005_remove_resource_teachers_re_course__c37675_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'تصنيف', 'verbose_name_plural': 'تصنيفات'},
        ),
        migrations.AlterField(
            model_name='product',
            name='course',
            field=models.ForeignKey(blank=True, help_text='اختياري: اربط هذا المنتج بدورة ليتم تفعيلها للطالب بعد الدفع.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='teachers.course', verbose_name='الدورة المرتبطة'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='store_categ_name_1278fd_idx'),
        ),
    ]
