# Generated by Django 5.2.4 on 2025-08-22 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_category_options_alter_product_course_and_more'),
        ('teachers', '0006_alter_course_code_alter_resource_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='اسم الطالب')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الجوال')),
                ('stage', models.CharField(blank=True, max_length=100, verbose_name='المرحلة')),
                ('subjects', models.TextField(blank=True, verbose_name='المواد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحجز')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='teachers.course', verbose_name='الدورة')),
            ],
            options={
                'verbose_name': 'حجز',
                'verbose_name_plural': 'حجوزات',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['course'], name='store_booki_course__817a1d_idx'), models.Index(fields=['created_at'], name='store_booki_created_c23280_idx')],
            },
        ),
    ]
