# Generated by Django 5.2.4 on 2025-08-22 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_booking'),
        ('teachers', '0006_alter_course_code_alter_resource_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='teachers.course', verbose_name='الدورة (اختياري)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='stage',
            field=models.CharField(blank=True, max_length=100, verbose_name='المرحلة الدراسية'),
        ),
    ]
