# Generated by Django 5.2.4 on 2025-08-16 09:28

import django.utils.timezone
import teachers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_course_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='resource',
            name='file_url',
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.SlugField(blank=True, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lesson',
            name='slide_file',
            field=models.FileField(blank=True, null=True, upload_to=teachers.models.lecture_upload_to),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=teachers.models.lecture_upload_to),
        ),
        migrations.AddField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=teachers.models.material_upload_to),
        ),
        migrations.AddField(
            model_name='resource',
            name='kind',
            field=models.CharField(choices=[('book', 'كتاب/مرجع'), ('sheet', 'ملزمة/واجب'), ('slides', 'شرائح عرض'), ('other', 'أخرى')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active'], name='teachers_co_is_acti_cec60a_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='teachers_co_code_c2ad0b_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'order'], name='teachers_le_course__7251fa_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['course', 'kind'], name='teachers_re_course__c37675_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['name', 'stage'], name='teachers_su_name_c5f86c_idx'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='uniq_lesson_order_per_course'),
        ),
    ]
