# Generated by Django 5.2.4 on 2025-08-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_resource_options_remove_resource_file_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.SlugField(blank=True, help_text='يُولَّد تلقائيًا إن تُرك فارغًا', max_length=64, unique=True),
        ),
    ]
