# Generated by Django 5.2.4 on 2025-08-17 21:16

import django.core.validators
import teachers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_course_code'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='resource',
            name='teachers_re_course__c37675_idx',
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.SlugField(blank=True, help_text='يُولَّد تلقائيًا إن تُرك فارغًا (مشتق من العنوان + لاحقة زمنية).', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='teams_link',
            field=models.URLField(blank=True, verbose_name='رابط Microsoft Teams'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slide_file',
            field=models.FileField(blank=True, null=True, upload_to=teachers.models.lecture_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'ppt', 'pptx', 'pptm'])]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=teachers.models.lecture_upload_to, validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'mkv', 'webm'])]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=teachers.models.material_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'ppt', 'pptx', 'xlsx', 'pdf', 'ppt', 'pptx', 'pptm'])]),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['title'], name='teachers_co_title_f3d9c8_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['course', 'kind', 'created_at'], name='teachers_re_course__fea8df_idx'),
        ),
    ]
