# Generated by Django 5.2.4 on 2025-08-22 20:25

import django.core.validators
import teachers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_remove_resource_teachers_re_course__c37675_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.SlugField(blank=True, help_text='يُولَّد تلقائيًا إن تُرك فارغًا.', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=teachers.models.material_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'ppt', 'pptx', 'xlsx', 'zip', 'pdf', 'ppt', 'pptx', 'pptm'])]),
        ),
    ]
