# Generated by Django 5.2.4 on 2025-08-19 02:45

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_remove_order_ordered_at_and_more'),
        ('store', '0005_alter_category_options_alter_product_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='سعر المنتج لحظة إنشاء الطلب (لقطة سعر).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر وقت الطلب'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['product'], name='orders_orde_product_cacc30_idx'),
        ),
    ]
